### ISSUE TITLE
Issues with storex-sync

### ISSUE THREAD

**Issue by ohxh** [WorldBrain/storex-frontend-boilerplate#4]
This repository seems to reference modules in storex-sync that don't exist, at least in the version on github and NPM (see below). Is there any version of this repo that can be cloned and run with what's publicly available today?

Module not found: Can't resolve '@worldbrain/storex-sync/lib/integration/continuous-sync' in '/Users/oliverhopcroft/development/storex-frontend-boilerplate/src/services'

**Comment by ShishKabab** [comment]
This module hasn't been touched in quite a while and the code is probably not up to date. Also right now, we don't really have the resources to keep it up to date ourselves, since few people are using Storex outside WorldBrain yet. If you're checking out what Storex is and whether it could be useful to you, I'd be happy to give you some guidance and jump on a call. If you'd like to help bring this repo up to date, I can also help to do that.

**Comment by ohxh** [comment]
Thanks for getting back to me--I'm just checking out storex for a project I'm working on. If you still have time to hop on a call, send me an email at oliverhopcroft@gmail.com with a time you're free and we can go from there.
